"""Add MovieDataset model

Revision ID: 05e898d99ea2
Revises: 17f1be643b26
Create Date: 2025-11-04 00:12:51.087781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e898d99ea2'
down_revision = '17f1be643b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_dataset',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=500), nullable=True),
    sa.Column('production_company', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('imdb_votes', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('poster_local_path', sa.String(length=500), nullable=True),
    sa.Column('screenplay', sa.JSON(), nullable=True),
    sa.Column('cast', sa.JSON(), nullable=True),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_type', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_dataset')
    # ### end Alembic commands ###
