"""Add movie table

Revision ID: 05662d95869a
Revises: 05e898d99ea2
Create Date: 2025-11-09 23:32:57.017913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05662d95869a'
down_revision = '05e898d99ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_dataset_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=500), nullable=True),
    sa.Column('production_company', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('imdb_votes', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('poster_local_path', sa.String(length=500), nullable=True),
    sa.Column('screenplay', sa.JSON(), nullable=True),
    sa.Column('cast', sa.JSON(), nullable=True),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['movie_dataset_id'], ['movie_dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('webhook')
    with op.batch_alter_table('base_dataset', schema=None) as batch_op:
        batch_op.alter_column('total_size_bytes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('total_size_human',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('files')

    with op.batch_alter_table('movie_dataset', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('movie_dataset_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'base_dataset', ['id'], ['id'])
        batch_op.drop_column('imdb_votes')
        batch_op.drop_column('poster_local_path')
        batch_op.drop_column('country')
        batch_op.drop_column('genre')
        batch_op.drop_column('production_company')
        batch_op.drop_column('awards')
        batch_op.drop_column('director')
        batch_op.drop_column('original_title')
        batch_op.drop_column('cast')
        batch_op.drop_column('imdb_rating')
        batch_op.drop_column('duration')
        batch_op.drop_column('synopsis')
        batch_op.drop_column('screenplay')
        batch_op.drop_column('year')
        batch_op.drop_column('movie_title')
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('movie_title', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('screenplay', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('synopsis', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imdb_rating', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cast', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('original_title', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('director', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('awards', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('production_company', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('genre', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_local_path', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('imdb_votes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('movie_dataset_ibfk_1'), 'base_dataset', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('base_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('files', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.alter_column('total_size_human',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('total_size_bytes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('movie')
    # ### end Alembic commands ###
