"""add logo_url to community

Revision ID: 58bb2d9c6524
Revises: 46a26f8ced76
Create Date: 2025-12-13 00:08:50.533328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58bb2d9c6524'
down_revision = '46a26f8ced76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###

