"""Ensure doi field in Fakenodo

Revision ID: fae8063a53ec
Revises: 961f256fbc21
Create Date: 2025-12-03 11:19:54.164769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae8063a53ec'
down_revision = '961f256fbc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakenodo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doi', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakenodo', schema=None) as batch_op:
        batch_op.drop_column('doi')

    # ### end Alembic commands ###
