# ----------------------------------------------------------------------------
# Feature Branch Workflow
# ----------------------------------------------------------------------------
# This workflow validates temporary branches and automatically merges into develop.
# Supported branches: feature/*, fix/*, test/*
# ----------------------------------------------------------------------------

name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'test/*'

jobs:
  validate-branch:
    name: Validate Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Check Format
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Detected branch: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^(feature|fix|test)\/[a-zA-Z0-9._-]+$ ]]; then
            echo "Invalid format. Use type/name supported"
            exit 1
          fi

          echo "Branch format OK."

  merge-to-develop:
    name: Auto Merge to Develop
    runs-on: ubuntu-latest
    needs: validate-branch
    if: success()
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "AutoMerge Bot"
          git config user.email "bot@repo.local"

      - name: Merge to develop
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Merging $BRANCH_NAME → develop"

          git fetch --all
          git checkout develop
          git merge --no-ff "$BRANCH_NAME" -m "Auto-merge from $BRANCH_NAME"
          git push origin develop

          echo "Merge completed."

  cleanup:
    name: Delete Temporary Branch
    runs-on: ubuntu-latest
    needs: merge-to-develop
    steps:
      - name: Delete Remote Branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Deleting remote branch $BRANCH_NAME"
          git fetch origin
          git push origin --delete "$BRANCH_NAME" || true
          echo "Remote branch $BRANCH_NAME deleted"
