name: Deploy to Render

on:
  push:
    branches:
      main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ./

      - name: Populate Database
        env:
          FLASK_ENV: production
          MARIADB_HOSTNAME: ${{ secrets.MARIADB_HOSTNAME }}
          MARIADB_PORT: ${{ secrets.MARIADB_PORT }}
          MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
          MARIADB_USER: ${{ secrets.MARIADB_USER }}
          MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
        run: |
          flask db upgrade  
          rosemary db:seed

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$deploy_url"